# Generated by Django 5.2.11 on 2026-03-11 17:00

import api.models.state_management
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DerivedArtifactRefresh",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("artifact_name", models.CharField(max_length=64, unique=True)),
                ("definition_hash", models.CharField(max_length=64)),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("last_row_count", models.BigIntegerField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=16,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "db_table": "DerivedArtifactRefresh",
                "ordering": ["artifact_name"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("mrn", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("last_name", models.CharField(max_length=30, null=True)),
                ("first_name", models.CharField(max_length=30, null=True)),
                ("birth_date", models.DateField(null=True)),
                ("sex_code", models.CharField(max_length=80, null=True)),
                ("race_desc", models.CharField(max_length=80, null=True)),
                ("ethnicity_desc", models.CharField(max_length=2000, null=True)),
                ("death_date", models.DateField(null=True)),
            ],
            options={
                "db_table": "Patient",
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="New State", max_length=128, unique=True)),
                ("definition", models.TextField()),
                ("owner", models.CharField(default="NA", max_length=128)),
                ("public", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                ("visit_no", models.BigIntegerField(primary_key=True, serialize=False)),
                ("epic_pat_id", models.CharField(max_length=80, null=True)),
                ("hsp_account_id", models.CharField(max_length=80, null=True)),
                ("adm_dtm", models.DateField(null=True)),
                ("dsch_dtm", models.DateField(null=True)),
                ("clinical_los", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("age_at_adm", models.FloatField(null=True)),
                ("pat_class_desc", models.CharField(max_length=2000, null=True)),
                ("pat_expired_f", models.CharField(max_length=1, null=True)),
                ("invasive_vent_f", models.CharField(max_length=1, null=True)),
                ("total_vent_mins", models.FloatField(null=True)),
                ("total_vent_days", models.FloatField(null=True)),
                ("apr_drg_code", models.CharField(max_length=254, null=True)),
                ("apr_drg_rom", models.CharField(max_length=80, null=True)),
                ("apr_drg_soi", models.CharField(max_length=80, null=True)),
                ("apr_drg_desc", models.CharField(max_length=2000, null=True)),
                ("apr_drg_weight", models.FloatField(null=True)),
                ("ms_drg_weight", models.FloatField(null=True)),
                ("cci_mi", models.FloatField(null=True)),
                ("cci_chf", models.FloatField(null=True)),
                ("cci_pvd", models.FloatField(null=True)),
                ("cci_cvd", models.FloatField(null=True)),
                ("cci_dementia", models.FloatField(null=True)),
                ("cci_copd", models.FloatField(null=True)),
                ("cci_rheum_dz", models.FloatField(null=True)),
                ("cci_pud", models.FloatField(null=True)),
                ("cci_liver_dz_mild", models.FloatField(null=True)),
                ("cci_dm_wo_compl", models.FloatField(null=True)),
                ("cci_dm_w_compl", models.FloatField(null=True)),
                ("cci_paraplegia", models.FloatField(null=True)),
                ("cci_renal_dz", models.FloatField(null=True)),
                ("cci_malign_wo_mets", models.FloatField(null=True)),
                ("cci_liver_dz_severe", models.FloatField(null=True)),
                ("cci_malign_w_mets", models.FloatField(null=True)),
                ("cci_hiv_aids", models.FloatField(null=True)),
                ("cci_score", models.FloatField(null=True)),
                ("mrn", models.ForeignKey(db_column="mrn", on_delete=django.db.models.deletion.CASCADE, to="api.patient")),
            ],
            options={
                "db_table": "Visit",
            },
        ),
        migrations.CreateModel(
            name="Transfusion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("trnsfsn_dtm", models.DateTimeField(null=True)),
                ("transfusion_rank", models.FloatField(null=True)),
                ("blood_unit_number", models.CharField(max_length=600, null=True)),
                ("rbc_units", models.FloatField(null=True)),
                ("ffp_units", models.FloatField(null=True)),
                ("plt_units", models.FloatField(null=True)),
                ("cryo_units", models.FloatField(null=True)),
                ("whole_units", models.FloatField(null=True)),
                ("rbc_vol", models.FloatField(null=True)),
                ("ffp_vol", models.FloatField(null=True)),
                ("plt_vol", models.FloatField(null=True)),
                ("cryo_vol", models.FloatField(null=True)),
                ("whole_vol", models.FloatField(null=True)),
                ("cell_saver_ml", models.FloatField(null=True)),
                ("visit_no", models.ForeignKey(db_column="visit_no", on_delete=django.db.models.deletion.CASCADE, to="api.visit")),
            ],
            options={
                "db_table": "Transfusion",
                "indexes": [models.Index(fields=["visit_no", "trnsfsn_dtm"], name="idx_transfusion_visit_dtm")],
            },
        ),
        migrations.CreateModel(
            name="SurgeryCase",
            fields=[
                ("case_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("case_date", models.DateField(null=True)),
                ("surgery_start_dtm", models.DateTimeField(null=True)),
                ("surgery_end_dtm", models.DateTimeField(null=True)),
                ("surgery_elap", models.FloatField(null=True)),
                ("surgery_type_desc", models.CharField(max_length=2000, null=True)),
                ("surgeon_prov_id", models.CharField(max_length=25, null=True)),
                ("surgeon_prov_name", models.CharField(max_length=100, null=True)),
                ("anesth_prov_id", models.CharField(max_length=25, null=True)),
                ("anesth_prov_name", models.CharField(max_length=100, null=True)),
                ("prim_proc_desc", models.CharField(max_length=2000, null=True)),
                ("postop_icu_los", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("sched_site_desc", models.CharField(max_length=2000, null=True)),
                ("asa_code", models.CharField(max_length=80, null=True)),
                ("mrn", models.ForeignKey(db_column="mrn", on_delete=django.db.models.deletion.CASCADE, to="api.patient")),
                ("visit_no", models.ForeignKey(db_column="visit_no", on_delete=django.db.models.deletion.CASCADE, to="api.visit")),
            ],
            options={
                "db_table": "SurgeryCase",
                "indexes": [models.Index(fields=["visit_no", "surgery_end_dtm"], name="idx_surgcase_visit_end")],
            },
        ),
        migrations.CreateModel(
            name="RoomTrace",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("department_id", models.CharField(max_length=30, null=True)),
                ("department_name", models.CharField(max_length=100, null=True)),
                ("room_id", models.CharField(max_length=30, null=True)),
                ("bed_id", models.CharField(max_length=30, null=True)),
                ("service_in_c", models.CharField(max_length=10, null=True)),
                ("service_in_desc", models.CharField(max_length=100, null=True)),
                ("in_dtm", models.DateTimeField(null=True)),
                ("out_dtm", models.DateTimeField(null=True)),
                ("duration_days", models.FloatField(null=True)),
                ("bed_room_dept_line", models.FloatField(null=True)),
                ("visit_no", models.ForeignKey(db_column="visit_no", on_delete=django.db.models.deletion.CASCADE, to="api.visit")),
            ],
            options={
                "db_table": "RoomTrace",
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_med_id", models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ("order_dtm", models.DateTimeField(null=True)),
                ("medication_id", models.DecimalField(decimal_places=0, max_digits=18, null=True)),
                ("medication_name", models.CharField(max_length=510, null=True)),
                ("med_admin_line", models.DecimalField(decimal_places=0, max_digits=38, null=True)),
                ("admin_dtm", models.DateTimeField(null=True)),
                ("admin_dose", models.CharField(max_length=184, null=True)),
                ("med_form", models.CharField(max_length=50, null=True)),
                ("admin_route_desc", models.CharField(max_length=254, null=True)),
                ("dose_unit_desc", models.CharField(max_length=254, null=True)),
                ("med_start_dtm", models.DateTimeField(null=True)),
                ("med_end_dtm", models.DateTimeField(null=True)),
                ("visit_no", models.ForeignKey(db_column="visit_no", on_delete=django.db.models.deletion.CASCADE, to="api.visit")),
            ],
            options={
                "db_table": "Medication",
            },
        ),
        migrations.CreateModel(
            name="Lab",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lab_id", models.CharField(max_length=64, null=True)),
                ("lab_draw_dtm", models.DateTimeField(null=True)),
                ("lab_panel_code", models.CharField(max_length=30, null=True)),
                ("lab_panel_desc", models.CharField(max_length=256, null=True)),
                ("result_dtm", models.DateTimeField(null=True)),
                ("result_code", models.CharField(max_length=30, null=True)),
                ("result_loinc", models.CharField(max_length=30, null=True)),
                ("result_desc", models.CharField(max_length=256, null=True)),
                ("result_value", models.CharField(max_length=256, null=True)),
                ("uom_code", models.CharField(max_length=30, null=True)),
                ("lower_limit", models.CharField(max_length=256, null=True)),
                ("upper_limit", models.CharField(max_length=256, null=True)),
                ("mrn", models.ForeignKey(db_column="mrn", on_delete=django.db.models.deletion.CASCADE, to="api.patient")),
                ("visit_no", models.ForeignKey(db_column="visit_no", on_delete=django.db.models.deletion.CASCADE, to="api.visit")),
            ],
            options={
                "db_table": "Lab",
                "indexes": [
                    models.Index(
                        fields=["visit_no", "lab_draw_dtm", "result_desc", "result_value"],
                        name="idx_lab_visit_draw_desc_val",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BillingCode",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cpt_code", models.CharField(max_length=80, null=True)),
                ("cpt_code_desc", models.CharField(max_length=2000, null=True)),
                ("proc_dtm", models.DateTimeField(null=True)),
                ("prov_id", models.CharField(max_length=25, null=True)),
                ("prov_name", models.CharField(max_length=100, null=True)),
                ("code_rank", models.FloatField(null=True)),
                ("visit_no", models.ForeignKey(db_column="visit_no", on_delete=django.db.models.deletion.CASCADE, to="api.visit")),
            ],
            options={
                "db_table": "BillingCode",
                "indexes": [
                    models.Index(fields=["cpt_code", "visit_no"], name="billingcode_cpt_visit_idx"),
                    models.Index(fields=["visit_no", "cpt_code"], name="idx_billingcode_visit_cpt"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendingProvider",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prov_id", models.CharField(max_length=25, null=True)),
                ("prov_name", models.CharField(max_length=100, null=True)),
                ("attend_start_dtm", models.DateTimeField(null=True)),
                ("attend_end_dtm", models.DateTimeField(null=True)),
                ("attend_prov_line", models.DecimalField(decimal_places=0, max_digits=38, null=True)),
                ("visit_no", models.ForeignKey(db_column="visit_no", on_delete=django.db.models.deletion.CASCADE, to="api.visit")),
            ],
            options={
                "db_table": "AttendingProvider",
                "indexes": [
                    models.Index(
                        fields=["visit_no", "attend_start_dtm", "attend_end_dtm", "prov_id", "attend_prov_line"],
                        name="idx_attprov_visit_dtm_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StateAccess",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[("READER", "RE"), ("WRITER", "WR")],
                        default=api.models.state_management.AccessLevel["READER"],
                        max_length=6,
                    ),
                ),
                ("state", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.state")),
            ],
            options={
                "unique_together": {("state", "user")},
            },
        ),
    ]
