# Generated by Django 5.2.12 on 2026-04-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDepartment',
            fields=[
                ('prov_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('department_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ProviderDepartment',
            },
        ),
        migrations.AddIndex(
            model_name='roomtrace',
            index=models.Index(fields=['visit_no', 'in_dtm', 'out_dtm'], name='roomtrace_visit_window_idx'),
        ),
        migrations.AddIndex(
            model_name='providerdepartment',
            index=models.Index(fields=['department_id'], name='provdept_dept_id_idx'),
        ),
    ]
