# Generated by Django 2.1.15 on 2020-05-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='name',
            field=models.CharField(default='New State', max_length=128, unique=True),
        ),
    ]
