# Generated by Django 5.2.1 on 2025-09-17 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidelineAdherence',
            fields=[
                ('visit_no', models.OneToOneField(db_column='visit_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='guideline_adherence', serialize=False, to='api.visit')),
                ('rbc_adherent', models.IntegerField()),
                ('ffp_adherent', models.IntegerField()),
                ('plt_adherent', models.IntegerField()),
                ('cryo_adherent', models.IntegerField()),
            ],
            options={
                'db_table': 'GuidelineAdherence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisitAttributes',
            fields=[
                ('visit_no', models.OneToOneField(db_column='visit_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attributes', serialize=False, to='api.visit')),
                ('adm_dtm', models.DateField()),
                ('dsch_dtm', models.DateField()),
                ('age_at_adm', models.IntegerField()),
                ('pat_class_desc', models.CharField(max_length=100)),
                ('apr_drg_weight', models.FloatField()),
                ('month', models.CharField(max_length=8)),
                ('quarter', models.CharField(max_length=7)),
                ('year', models.CharField(max_length=4)),
                ('rbc_units', models.IntegerField()),
                ('ffp_units', models.IntegerField()),
                ('plt_units', models.IntegerField()),
                ('cryo_units', models.IntegerField()),
                ('whole_units', models.IntegerField()),
                ('los', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('death', models.BooleanField()),
                ('vent', models.BooleanField()),
                ('stroke', models.BooleanField()),
                ('ecmo', models.BooleanField()),
                ('b12', models.BooleanField()),
                ('iron', models.BooleanField()),
                ('antifibrinolytic', models.BooleanField()),
                ('rbc_adherent', models.IntegerField()),
                ('ffp_adherent', models.IntegerField()),
                ('plt_adherent', models.IntegerField()),
                ('cryo_adherent', models.IntegerField()),
                ('overall_adherent', models.IntegerField()),
                ('rbc_units_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ffp_units_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('plt_units_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cryo_units_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('overall_cost', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'VisitAttributes',
                'managed': False,
            },
        ),
    ]
