# Generated by Django 5.2.12 on 2026-04-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDepartmentMapping',
            fields=[
                ('prov_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ProviderDepartmentMapping',
            },
        ),
    ]
