# Generated by Django 2.2.15 on 2020-08-26 18:55

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='owner',
            field=models.CharField(default='NA', max_length=128),
        ),
        migrations.CreateModel(
            name='StateAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('READER', 'RE'), ('WRITER', 'WR')], default=api.models.AccessLevel('RE'), max_length=2)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.State')),
            ],
        ),
    ]
