# Generated by Django 5.2.7 on 2025-10-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_manual_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAttributes',
            fields=[
                ('prov_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('prov_name', models.CharField(db_index=True, max_length=100)),
                ('surgery_count', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'ProviderAttributes',
                'managed': False,
            },
        ),
    ]
