# Generated by Django 5.2.9 on 2025-12-15 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_manual_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuidelineAdherence',
        ),
    ]
