# Generated by Django 2.2.24 on 2021-07-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210716_1709'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stateaccess',
            unique_together={('state', 'user')},
        ),
    ]
