# Generated by Django 5.2.9 on 2026-02-19 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_surgery_case_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuidelineAdherence',
        ),
    ]
