# Generated by Django 5.2.11 on 2026-02-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_billingcode_cpt_visit_idx'),
        ('api', '0005_delete_guidelineadherence'),
    ]

    operations = [
    ]
