# Generated by Django 5.2.11 on 2026-02-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20260225_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryCaseAttributes',
            fields=[
                ('case_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('surgeon_prov_id', models.CharField(max_length=25)),
                ('surgeon_prov_name', models.CharField(max_length=100)),
                ('anesth_prov_id', models.CharField(max_length=25)),
                ('anesth_prov_name', models.CharField(max_length=100)),
                ('surgery_start_dtm', models.DateTimeField()),
                ('surgery_end_dtm', models.DateTimeField()),
                ('case_date', models.DateField()),
                ('month', models.CharField(max_length=8)),
                ('quarter', models.CharField(max_length=7)),
                ('year', models.CharField(max_length=4)),
                ('pre_hgb', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('pre_plt', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('pre_fibrinogen', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('pre_inr', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('post_hgb', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('post_plt', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('post_fibrinogen', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('post_inr', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('intraop_rbc_units', models.PositiveSmallIntegerField(default=0)),
                ('intraop_ffp_units', models.PositiveSmallIntegerField(default=0)),
                ('intraop_plt_units', models.PositiveSmallIntegerField(default=0)),
                ('intraop_cryo_units', models.PositiveSmallIntegerField(default=0)),
                ('intraop_whole_units', models.PositiveSmallIntegerField(default=0)),
                ('intraop_cell_saver_ml', models.PositiveIntegerField(default=0)),
                ('los', models.FloatField(null=True)),
                ('death', models.BooleanField(null=True)),
                ('vent', models.BooleanField(null=True)),
                ('stroke', models.BooleanField(null=True)),
                ('ecmo', models.BooleanField(null=True)),
                ('rbc_cost', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('ffp_cost', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('plt_cost', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('cryo_cost', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('whole_cost', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('cell_saver_cost', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'SurgeryCaseAttributes',
                'managed': False,
            },
        ),
    ]
