# Generated by Django 5.2.11 on 2026-03-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_null_safe_visit_attributes_provider_line'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendingprovider',
            index=models.Index(fields=['visit_no', 'attend_start_dtm', 'attend_end_dtm', 'prov_id', 'attend_prov_line'], name='idx_attprov_visit_dtm_range'),
        ),
        migrations.AddIndex(
            model_name='billingcode',
            index=models.Index(fields=['visit_no', 'cpt_code'], name='idx_billingcode_visit_cpt'),
        ),
        migrations.AddIndex(
            model_name='lab',
            index=models.Index(fields=['visit_no', 'lab_draw_dtm', 'result_desc', 'result_value'], name='idx_lab_visit_draw_desc_val'),
        ),
        migrations.AddIndex(
            model_name='surgerycase',
            index=models.Index(fields=['visit_no', 'surgery_end_dtm'], name='idx_surgcase_visit_end'),
        ),
        migrations.AddIndex(
            model_name='transfusion',
            index=models.Index(fields=['visit_no', 'trnsfsn_dtm'], name='idx_transfusion_visit_dtm'),
        ),
    ]
