# Generated by Django 2.2.24 on 2021-07-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200826_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='owner',
            field=models.CharField(default='u0999308', max_length=128),
        ),
    ]
