services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:Z
    entrypoint: []
    command:
      - /bin/sh
      - -c
      - poetry run python manage.py migrate --noinput && poetry run python manage.py runserver 0.0.0.0:8000
    tty: true

  mariadb:
    extends:
      file: docker-compose.yml
      service: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/conf.d:/etc/mysql/conf.d:z
      - ./mariadb/initdb:/docker-entrypoint-initdb.d:z

volumes:
  mariadb_data:
  backend_parquets:
