services:
  backend:
    image: ghcr.io/visdesignlab/django-image:3.2-v0.0.14
    volumes:
      - .:/app:Z
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=this-is-not-secret
      - REQUIRE_LOGINS=False
      - MYSQL_DB=sanguine
      - MYSQL_USER=sanguine
      - MYSQL_PASSWORD=test
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
      - ORACLE_HOST=
      - ORACLE_PORT=
      - ORACLE_SERVICE_NAME=
    ports:
      - "8000:8000"

  mariadb:
    image: mariadb:10
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: sanguine
      MARIADB_USER: sanguine
      MARIADB_PASSWORD: test
    ports:
      - "3306:3306"

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ../frontend:/app
    environment:
      - NODE_ENV=production"
    command: sh -c "yarn install && yarn run build"
