name: Bug report
description: Report a bug you've encountered
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe your bug
      description: 1. Describe your bug  2. Steps to reproduce it  3. Include screenshots and/or recordings
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
