name: Bug report
description: Report a bug you've encountered
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe your bug
      description: Describe your bug and the steps to reproduce it
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If you can, provide screen-shots or screen recordings of this bug.
    validations:
      required: false
