name: Feature request
description: Suggest a new feature or improvement
labels: [feature request]
body:
  - type: textarea
    id: describe-request
    attributes:
      label: Describe your request
      description: Describe the new feature or improvement you'd suggest
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Optionally, attach screenshots to explain your request
    validations:
      required: false
