import { ExploreTableData } from '../../../../Types/application';

// ...existing code...
export type Row = {
  id: number;
  vent: number; // percent
  b12: number; // percent
  surgeon_prov_id: string; // array
  cases: number;
  drg_weight: number;
  percent_1_rbc: number;
  percent_2_rbc: number;
  percent_3_rbc: number;
  percent_4_rbc: number;
  percent_5_rbc: number;
  // new cost fields (now average cost per case)
  rbc_cost: number;
  ffp_cost: number;
  platelets_cost: number;
  cryo_cost: number;
  salvage_savings: number;
};

export const dummyData = [
  {
    id: 1,
    vent: 0,
    b12: 72,
    surgeon_prov_id: 'Dr. Smith',
    cases: 42,
    percent_1_rbc: 40,
    percent_2_rbc: 30,
    percent_3_rbc: 20,
    percent_4_rbc: 7,
    percent_5_rbc: 3,
    // average costs (per case)
    rbc_cost: 24,
    ffp_cost: 9,
    platelets_cost: 7,
    cryo_cost: 3,
    salvage_savings: 5,
  },
  {
    id: 2,
    vent: 85,
    b12: 72,
    surgeon_prov_id: 'Dr. Lee',
    cases: 42,
    percent_1_rbc: 30,
    percent_2_rbc: 25,
    percent_3_rbc: 20,
    percent_4_rbc: 15,
    percent_5_rbc: 10,
    rbc_cost: 23,
    ffp_cost: 9,
    platelets_cost: 8,
    cryo_cost: 4,
    salvage_savings: 5,
  },
  {
    id: 3,
    vent: 12,
    b12: 8,
    surgeon_prov_id: 'Dr. Patel',
    cases: 5,
    percent_1_rbc: 0,
    percent_2_rbc: 50,
    percent_3_rbc: 0,
    percent_4_rbc: 50,
    percent_5_rbc: 0,
    rbc_cost: 35,
    ffp_cost: 14,
    platelets_cost: 11,
    cryo_cost: 6,
    salvage_savings: 8,
  },
  {
    id: 4,
    vent: 55,
    b12: 60,
    surgeon_prov_id: 'Dr. Gomez',
    cases: 18,
    percent_1_rbc: 20,
    percent_2_rbc: 20,
    percent_3_rbc: 10,
    percent_4_rbc: 10,
    percent_5_rbc: 0,
    rbc_cost: 26,
    ffp_cost: 10,
    platelets_cost: 8,
    cryo_cost: 4,
    salvage_savings: 6,
  },
  {
    id: 5,
    vent: 55,
    b12: 60,
    surgeon_prov_id: 'Dr. Park',
    cases: 18,
    percent_1_rbc: 18,
    percent_2_rbc: 25,
    percent_3_rbc: 18,
    percent_4_rbc: 10,
    percent_5_rbc: 9,
    rbc_cost: 25,
    ffp_cost: 9,
    platelets_cost: 8,
    cryo_cost: 4,
    salvage_savings: 5,
  },
  {
    id: 6,
    vent: 55,
    b12: 60,
    surgeon_prov_id: 'Dr. Huang',
    cases: 18,
    percent_1_rbc: 33,
    percent_2_rbc: 33,
    percent_3_rbc: 34,
    percent_4_rbc: 0,
    percent_5_rbc: 0,
    rbc_cost: 24,
    ffp_cost: 9,
    platelets_cost: 8,
    cryo_cost: 4,
    salvage_savings: 5,
  },
  {
    id: 7,
    vent: 98,
    b12: 93,
    surgeon_prov_id: 'Dr. Nguyen',
    cases: 120,
    percent_1_rbc: 28,
    percent_2_rbc: 28,
    percent_3_rbc: 22,
    percent_4_rbc: 12,
    percent_5_rbc: 10,
    // higher volume -> slightly lower average costs
    rbc_cost: 18,
    ffp_cost: 7,
    platelets_cost: 6,
    cryo_cost: 3,
    salvage_savings: 4,
  },
  {
    id: 8,
    vent: 30,
    b12: 40,
    surgeon_prov_id: 'Dr. Alvarez',
    cases: 9,
    percent_1_rbc: 33,
    percent_2_rbc: 0,
    percent_3_rbc: 33,
    percent_4_rbc: 34,
    percent_5_rbc: 0,
    rbc_cost: 30,
    ffp_cost: 12,
    platelets_cost: 10,
    cryo_cost: 5,
    salvage_savings: 6,
  },
  {
    id: 9,
    vent: 30,
    b12: 40,
    surgeon_prov_id: 'Dr. Chen',
    cases: 9,
    percent_1_rbc: 0,
    percent_2_rbc: 0,
    percent_3_rbc: 0,
    percent_4_rbc: 11,
    percent_5_rbc: 0,
    rbc_cost: 29,
    ffp_cost: 11,
    platelets_cost: 9,
    cryo_cost: 4,
    salvage_savings: 5,
  },
  // additional synthetic records (costs as averages; higher-volume surgeons slightly cheaper)
  {
    id: 10,
    vent: 67,
    b12: 70,
    surgeon_prov_id: 'Dr. Rivera',
    cases: 36,
    percent_1_rbc: 25,
    percent_2_rbc: 20,
    percent_3_rbc: 30,
    percent_4_rbc: 15,
    percent_5_rbc: 10,
    rbc_cost: 22,
    ffp_cost: 9,
    platelets_cost: 8,
    cryo_cost: 3,
    salvage_savings: 5,
  },
  {
    id: 11,
    vent: 45,
    b12: 50,
    surgeon_prov_id: 'Dr. Johnson',
    cases: 22,
    percent_1_rbc: 40,
    percent_2_rbc: 30,
    percent_3_rbc: 10,
    percent_4_rbc: 15,
    percent_5_rbc: 5,
    rbc_cost: 21,
    ffp_cost: 8,
    platelets_cost: 6,
    cryo_cost: 3,
    salvage_savings: 4,
  },
  {
    id: 12,
    vent: 12,
    b12: 20,
    surgeon_prov_id: 'Dr. Williams',
    cases: 7,
    percent_1_rbc: 0,
    percent_2_rbc: 60,
    percent_3_rbc: 40,
    percent_4_rbc: 0,
    percent_5_rbc: 0,
    rbc_cost: 32,
    ffp_cost: 13,
    platelets_cost: 10,
    cryo_cost: 5,
    salvage_savings: 6,
  },
  {
    id: 13,
    vent: 90,
    b12: 88,
    surgeon_prov_id: 'Dr. Brown',
    cases: 80,
    percent_1_rbc: 35,
    percent_2_rbc: 30,
    percent_3_rbc: 20,
    percent_4_rbc: 10,
    percent_5_rbc: 5,
    rbc_cost: 19,
    ffp_cost: 8,
    platelets_cost: 6,
    cryo_cost: 3,
    salvage_savings: 4,
  },
  {
    id: 14,
    vent: 20,
    b12: 18,
    surgeon_prov_id: 'Dr. Davis',
    cases: 6,
    percent_1_rbc: 0,
    percent_2_rbc: 0,
    percent_3_rbc: 80,
    percent_4_rbc: 20,
    percent_5_rbc: 0,
    rbc_cost: 34,
    ffp_cost: 14,
    platelets_cost: 11,
    cryo_cost: 6,
    salvage_savings: 8,
  },
  {
    id: 15,
    vent: 75,
    b12: 64,
    surgeon_prov_id: 'Dr. Miller',
    cases: 48,
    percent_1_rbc: 30,
    percent_2_rbc: 25,
    percent_3_rbc: 20,
    percent_4_rbc: 15,
    percent_5_rbc: 10,
    rbc_cost: 20,
    ffp_cost: 8,
    platelets_cost: 6,
    cryo_cost: 3,
    salvage_savings: 4,
  },
  {
    id: 16,
    vent: 58,
    b12: 55,
    surgeon_prov_id: 'Dr. Wilson',
    cases: 28,
    percent_1_rbc: 22,
    percent_2_rbc: 22,
    percent_3_rbc: 22,
    percent_4_rbc: 18,
    percent_5_rbc: 16,
    rbc_cost: 22,
    ffp_cost: 9,
    platelets_cost: 7,
    cryo_cost: 4,
    salvage_savings: 5,
  },
  {
    id: 17,
    vent: 33,
    b12: 36,
    surgeon_prov_id: 'Dr. Moore',
    cases: 12,
    percent_1_rbc: 50,
    percent_2_rbc: 30,
    percent_3_rbc: 10,
    percent_4_rbc: 10,
    percent_5_rbc: 0,
    rbc_cost: 27,
    ffp_cost: 11,
    platelets_cost: 9,
    cryo_cost: 5,
    salvage_savings: 6,
  },
  {
    id: 18,
    vent: 82,
    b12: 79,
    surgeon_prov_id: 'Dr. Taylor',
    cases: 64,
    percent_1_rbc: 30,
    percent_2_rbc: 25,
    percent_3_rbc: 20,
    percent_4_rbc: 15,
    percent_5_rbc: 10,
    rbc_cost: 18,
    ffp_cost: 7,
    platelets_cost: 6,
    cryo_cost: 3,
    salvage_savings: 4,
  },
  {
    id: 19,
    vent: 14,
    b12: 10,
    surgeon_prov_id: 'Dr. Anderson',
    cases: 4,
    percent_1_rbc: 0,
    percent_2_rbc: 75,
    percent_3_rbc: 0,
    percent_4_rbc: 25,
    percent_5_rbc: 0,
    rbc_cost: 36,
    ffp_cost: 15,
    platelets_cost: 12,
    cryo_cost: 6,
    salvage_savings: 9,
  },
  {
    id: 20,
    vent: 49,
    b12: 52,
    surgeon_prov_id: 'Dr. Thomas',
    cases: 20,
    percent_1_rbc: 30,
    percent_2_rbc: 30,
    percent_3_rbc: 20,
    percent_4_rbc: 10,
    percent_5_rbc: 10,
    rbc_cost: 23,
    ffp_cost: 9,
    platelets_cost: 7,
    cryo_cost: 3,
    salvage_savings: 4,
  },
  {
    id: 21,
    vent: 71,
    b12: 68,
    surgeon_prov_id: 'Dr. Jackson',
    cases: 44,
    percent_1_rbc: 28,
    percent_2_rbc: 26,
    percent_3_rbc: 24,
    percent_4_rbc: 12,
    percent_5_rbc: 10,
    rbc_cost: 22,
    ffp_cost: 9,
    platelets_cost: 7,
    cryo_cost: 3,
    salvage_savings: 5,
  },
  {
    id: 22,
    vent: 27,
    b12: 30,
    surgeon_prov_id: 'Dr. White',
    cases: 11,
    percent_1_rbc: 10,
    percent_2_rbc: 60,
    percent_3_rbc: 10,
    percent_4_rbc: 20,
    percent_5_rbc: 0,
    rbc_cost: 28,
    ffp_cost: 11,
    platelets_cost: 9,
    cryo_cost: 5,
    salvage_savings: 6,
  },
  {
    id: 23,
    vent: 94,
    b12: 90,
    surgeon_prov_id: 'Dr. Harris',
    cases: 95,
    percent_1_rbc: 40,
    percent_2_rbc: 30,
    percent_3_rbc: 15,
    percent_4_rbc: 10,
    percent_5_rbc: 5,
    rbc_cost: 18,
    ffp_cost: 7,
    platelets_cost: 6,
    cryo_cost: 3,
    salvage_savings: 4,
  },
  {
    id: 24,
    vent: 38,
    b12: 35,
    surgeon_prov_id: 'Dr. Martin',
    cases: 15,
    percent_1_rbc: 40,
    percent_2_rbc: 30,
    percent_3_rbc: 20,
    percent_4_rbc: 5,
    percent_5_rbc: 5,
    rbc_cost: 26,
    ffp_cost: 10,
    platelets_cost: 8,
    cryo_cost: 4,
    salvage_savings: 5,
  },
  {
    id: 25,
    vent: 60,
    b12: 58,
    surgeon_prov_id: 'Dr. Thompson',
    cases: 34,
    percent_1_rbc: 30,
    percent_2_rbc: 25,
    percent_3_rbc: 20,
    percent_4_rbc: 15,
    percent_5_rbc: 10,
    rbc_cost: 21,
    ffp_cost: 8,
    platelets_cost: 6,
    cryo_cost: 3,
    salvage_savings: 4,
  },
  {
    id: 26,
    vent: 52,
    b12: 48,
    surgeon_prov_id: 'Dr. Garcia',
    cases: 26,
    percent_1_rbc: 24,
    percent_2_rbc: 24,
    percent_3_rbc: 22,
    percent_4_rbc: 18,
    percent_5_rbc: 12,
    rbc_cost: 22,
    ffp_cost: 9,
    platelets_cost: 7,
    cryo_cost: 4,
    salvage_savings: 5,
  },
] as ExploreTableData;
// ...existing code...
