DROP TABLE IF EXISTS SurgeryCaseAttributes;

CREATE TABLE SurgeryCaseAttributes (
    case_id BIGINT PRIMARY KEY,
    visit_no BIGINT,
    mrn VARCHAR(20),
    surgeon_prov_id VARCHAR(25),
    surgeon_prov_name VARCHAR(100),
    anesth_prov_id VARCHAR(25),
    anesth_prov_name VARCHAR(100),
    surgery_start_dtm DATETIME,
    surgery_end_dtm DATETIME,
    case_date DATE,
    month CHAR(8),
    quarter CHAR(7),
    year CHAR(4),
    pre_hgb DECIMAL(10, 4),
    pre_plt DECIMAL(10, 4),
    pre_fibrinogen DECIMAL(10, 4),
    pre_inr DECIMAL(10, 4),
    post_hgb DECIMAL(10, 4),
    post_plt DECIMAL(10, 4),
    post_fibrinogen DECIMAL(10, 4),
    post_inr DECIMAL(10, 4),
    intraop_rbc_units SMALLINT UNSIGNED DEFAULT 0,
    intraop_ffp_units SMALLINT UNSIGNED DEFAULT 0,
    intraop_plt_units SMALLINT UNSIGNED DEFAULT 0,
    intraop_cryo_units SMALLINT UNSIGNED DEFAULT 0,
    intraop_whole_units SMALLINT UNSIGNED DEFAULT 0,
    intraop_cell_saver_ml MEDIUMINT UNSIGNED DEFAULT 0,
    los FLOAT,
    death BOOLEAN,
    vent BOOLEAN,
    stroke BOOLEAN,
    ecmo BOOLEAN,
    rbc_cost DECIMAL(8,2),
    ffp_cost DECIMAL(8,2),
    plt_cost DECIMAL(8,2),
    cryo_cost DECIMAL(8,2),
    whole_cost DECIMAL(8,2),
    cell_saver_cost DECIMAL(8,2),
    total_cost DECIMAL(10,2),
    FOREIGN KEY (visit_no) REFERENCES Visit(visit_no) ON DELETE CASCADE,
    FOREIGN KEY (mrn) REFERENCES Patient(mrn) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;
