DROP TABLE IF EXISTS VisitAttributes;

CREATE TABLE VisitAttributes (
    id VARCHAR(50),
    visit_no BIGINT,
    mrn VARCHAR(20),
    adm_dtm DATE,
    dsch_dtm DATE,
    age_at_adm TINYINT UNSIGNED,
    pat_class_desc VARCHAR(100),
    apr_drg_weight FLOAT,
    ms_drg_weight FLOAT,
    month CHAR(8),
    quarter CHAR(7),
    year CHAR(4),
    rbc_units SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ffp_units SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    plt_units SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    cryo_units SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    whole_units SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    cell_saver_ml MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    overall_units SMALLINT UNSIGNED AS (rbc_units + ffp_units + plt_units + cryo_units + whole_units) STORED,
    los FLOAT,
    death BOOLEAN,
    vent BOOLEAN,
    stroke BOOLEAN,
    ecmo BOOLEAN,
    b12 BOOLEAN,
    iron BOOLEAN,
    antifibrinolytic BOOLEAN,
    rbc_units_adherent SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ffp_units_adherent SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    plt_units_adherent SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    cryo_units_adherent SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    overall_units_adherent SMALLINT UNSIGNED AS (rbc_units_adherent + ffp_units_adherent + plt_units_adherent + cryo_units_adherent) STORED,
    rbc_units_cost DECIMAL(6,2) GENERATED ALWAYS AS (rbc_units * 200.00) VIRTUAL,
    ffp_units_cost DECIMAL(6,2) GENERATED ALWAYS AS (ffp_units * 50.00) VIRTUAL,
    plt_units_cost DECIMAL(6,2) GENERATED ALWAYS AS (plt_units * 500.00) VIRTUAL,
    cryo_units_cost DECIMAL(6,2) GENERATED ALWAYS AS (cryo_units * 30.00) VIRTUAL,
    whole_units_cost DECIMAL(6,2) GENERATED ALWAYS AS (whole_units * 300.00) VIRTUAL,
    overall_cost DECIMAL(8,2) GENERATED ALWAYS AS ((rbc_units * 200.00) + (ffp_units * 50.00) + (plt_units * 500.00) + (cryo_units * 30.00) + (whole_units * 300.00)) VIRTUAL,
    attending_provider VARCHAR(100),
    attending_provider_id VARCHAR(25),
    attending_provider_line SMALLINT UNSIGNED DEFAULT 0,
    is_admitting_attending BOOLEAN,
    PRIMARY KEY (id),
    FOREIGN KEY (visit_no) REFERENCES Visit(visit_no),
    FOREIGN KEY (mrn) REFERENCES Patient(mrn)
) ENGINE=InnoDB ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;
